### ISSUE TITLE
Link "ver no site" não funciona

### ISSUE THREAD

**Issue by rsip22** [emaula/site#1]
![Interface administrativa do EmAula](https://user-images.githubusercontent.com/16676222/53096028-efbc2a80-34fc-11e9-9a1f-7a408a089222.png)

Quando logado na interface de administração, ao modificar uma aula e clicar em "Ver no site", usuário é redirecionado a uma URL no formato **BASE_URL/school/professor_lessons/{number}/**, o que resulta em "Professor matching query does not exist.". Não deveria buscar professor, deveria buscar a instância da aula.

Comportamento esperado: deveria ser redirecionado para a página específica daquela aula **BASE_URL/school/classroom/{number}**

**Comment by xicopetry** [comment]
Basta modificar a função **get_absolute_url** do model Classroom, deixando ela assim:

```python
def get_absolute_url(self):
    return reverse('school:classroom_detail', args=[str(self.id)])
```

O que estava faltando era a app name "school"

**Comment by rsip22** [comment]
Feito!
