### ISSUE TITLE
Ao salvar uma aula no admin ele cria objetos do tipo Link vazios

### ISSUE THREAD

**Issue by xicopetry** [emaula/site#11]
Ao editar ou salvar um novo objeto classroom no admin, ele cria automaticamente um novo registro do tipo Link.

Toda vez que eh salvo o registro ele cria um novo objeto classroom, ficando assim na tela de admin, depois de ter aberto o objeto e somente ter clicado em salvar:
<img width="821" alt="captura de tela 2017-09-12 as 9 45 50 pm" src="https://user-images.githubusercontent.com/6098725/30354594-cb98ef9a-9803-11e7-8ab5-30fa66f6837f.png">

E ficando assim na tela das lessons:
<img width="558" alt="captura de tela 2017-09-12 as 9 46 43 pm" src="https://user-images.githubusercontent.com/6098725/30354639-eef78abe-9803-11e7-8d5b-74d212279388.png">

Outra coisa que notei foi que o campo _url_ do objeto **Link** foi colocado como `blank=True`.
Não entendi o motivo disso, por que haveria um link sem url?

**Comment by rsip22** [comment]
Resolvido. Obrigada pela colaboração, @xicopetry !

**Comment by xicopetry** [comment]
Capaz, estamos aqui pra ajudar! :D
