### ISSUE TITLE
Não funciona upload de imagens

### ISSUE THREAD

**Issue by rsip22** [emaula/site#4]
Django não consegue salvar as imagens enviadas pelos users por causa de permissões do sistema operacional (sem contar que assume o nome do user ao interagir com o sistema, e não o nome django).

Possibilidade de resolução:
- Criar uma pasta pública onde qualquer user pode salvar, mas não deletar
- Carregar as imagens enviadas para um CDN
- Usar alguma app para lidar com upload de imagens

**Comment by xicopetry** [comment]
Não tenho certeza se o problema eh referente a permissões do sistema operacional.

Fiz os testes na minha maquina e verifiquei que os links dos arquivos de media não estavam funcionando. Isso se deve porque não havia a configuração para eles no arquivo urls.py principal do projeto.

Outra coisa que notei, foi que nos templates as imagens não estavam sendo referenciadas corretamente.

Estou fazendo um pull request com essas correções.

**Comment by rsip22** [comment]
Não resolve o problema no servidor.

Debug:
```
PermissionError at /admin/school/classroom/add/
[Errno 13] Permission denied: '/home/aula_admin/www/final/media/media/imagem.jpg'

Exception Location: /home/aula_admin/www/myvenv/lib/python3.4/site-packages/django/core/files/storage.py in _save, line 347
Python Executable: /home/aula_admin/www/myvenv/bin/uwsgi
**Request information**
USER renata

```

O que eu imagino que aconteça:

Quando vai fazer o upload do arquivo, user que está fazendo o upload (ex. renata) se torna dono dele e tenta gravar no sistema operacional. Esse user não existe no servidor e nem tem como criar um para cada pessoa que se inscreve no site.

Não acho que o problema esteja no código do Django em si, talvez esteja no uwsgi ou nas configurações do NGINX, até porque essas suas alterações funcionam localmente...

**Comment by xicopetry** [comment]
Hummm, poise, o problema deve ser outro mesmo.

Isso ocorre quando vc cria uma nova aula ou tbm ocorre quando vc edita uma aula ja existente?

**Comment by rsip22** [comment]
Ocorre nos dois casos o mesmo erro, ele simplesmente não permite que user carregue a imagem... (salve no sistema operacional).

**Comment by xicopetry** [comment]
Estranho.... talvez vc poderia colocar na configuração do servidor o debug=True, causar o erro, e depois mandar a tela do erro pra a gente poder investigar melhor onde está o problema

**Comment by rsip22** [comment]
Fiz deploy desse código em um container em VPS e não houve o problema de upload de imagens. O que me leva a concluir que o problema realmente está na configuração do servidor que o código do EmAula.xyz estava implementado.
