### ISSUE TITLE
Quais informações devem conter no arquivo secrets.json?

### ISSUE THREAD

**Issue by xicopetry** [emaula/site#6]
Ao realizar os passos descritos para iniciar o desenvolvimento, me deparei com o erro na hora em que o settings tenta abrir o arquivo secrets.

Acho valido adicionar na documentação um exemplo de como deveria ficar o arquivo secrets.json.

**Comment by rsip22** [comment]
Oi, @xicopetry ! 

Realmente, apanhei bastante nessa questão de organizar para que a SECRET_KEY não ficasse pública e ainda assim o projeto rodasse... obrigada por apontar que ainda assim estava dando problema.

Organizei novamente, baixei e testei aqui. Atualizei o README. Agora deve estar funcionando com o novo comando.

Avise se ainda tiver problema.

**Comment by xicopetry** [comment]
Acabei de baixar e rocar o projeto novamente, seguindo os passos do README.

Tudo funcionando certinho :D
