### ISSUE TITLE
Estao faltando as migrations para as apps lessons e school

### ISSUE THREAD

**Issue by xicopetry** [emaula/site#7]

**Comment by xicopetry** [comment]
Sem os arquivos de migrations o comando 'Migrate' nao saberá quais tabelas devem ser criadas

**Comment by rsip22** [comment]
Pelo que entendi, não se commita migrations para não dar conflitos no desenvolvimento. Você deve criá-las depois de baixar o projeto. O commit que dei há pouco deve possibilitar isso. Agradeço se puder testar as novas settings, acho que não vai ter problema para criar o banco de dados local agora.

**Comment by xicopetry** [comment]
Ainda não resolve o problema.
Pelo que sei a gente não deve deixar desenvolvedor fazer o _makemigrations_ na sua maquina, (a menos que ele faça modificações nos models). A gente deve mandar esses arquivos e deixar que ele apenas faça o _migrate_

Repare na documentação no arquivo README.md:
```
(myvenv)$ python manage.py migrate --settings=website.settings.base
(myvenv)$ python manage.py createsuperuser --settings=website.settings.base
```
Não eh dito que eh necessário fazer o '_makemigrations_', e isso me parece correto. Nao me recordo de ter usado algum outro projeto django em que eu tenha que fazer o _makemigrations_, todos que usei sempre só dizem para fazer o migrate.

Lembrando que, o _migrate_ na minha maquina nao vai funcionar, pois eu nao tenho os arquivos de migração na minha maquina.

Em uma pesquisa rapida, encontrei alguns topicos no stackoverflow que podem ajudar a responder essa questao:

https://stackoverflow.com/questions/28035119/should-i-be-adding-the-django-migration-files-in-the-gitignore-file

https://stackoverflow.com/questions/44027755/git-and-django-migrations-ignore-the-migrations-files

Espero ter ajudado 👍

**Comment by rsip22** [comment]
Sim, obrigada pela ajuda e pela contribuição!
