### ISSUE TITLE
Erro ao registrar um novo usuário em /school/register/

### ISSUE THREAD

**Issue by xicopetry** [emaula/site#9]
Ao acessar _/school/register/_ , preencher os campos e clicar em _Registrar_ eh gerado um erro:

```
DoesNotExist at /school/register/
Group matching query does not exist.
```
O erro ocorre quando a view tenta pegar do banco um grupo chamado **school_staff**, o que no meu caso obviamente esse grupo nao existe.
Uma possível solução seria adicionar esse grupo via initial data, assim toda vez que o banco de dados for criado ele ja terá esse objeto.
https://docs.djangoproject.com/en/1.11/howto/initial-data/

Ou, outra solução pode ser criar este grupo em tempo de execução, utilizando o comando **get_or_create()**
https://docs.djangoproject.com/en/1.11/ref/models/querysets/#get-or-create

**Comment by rsip22** [comment]
Esse issue já foi resolvido e inclusive testes funcionais o contemplam.

Obrigada pela colaboração, @relsi e @xicopetry !
